apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    
  - name: Admin Web API
    type: prometheus
    access: proxy
    url: http://admin-web-dev:8080/metrics
    editable: true
    
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-dev:6379
    database: 0
    editable: true